### ISSUE TITLE
Unification of line feed codes

### ISSUE THREAD

**Issue by btyanagawamg** [terasolunaorg/terasoluna-gfw-web-multi-blank#341]
## Description
Now, line feed code is mixed LF and CRLF.
We unify line feed codes in this repository to LF.

## Possible Solutions
- Unify line feed codes in this repository to LF.

## Affects Version/s
* 5.X.X.RELEASE
* 1.X.X.RELEASE

## Fix Version/s
- [x] 5.4.0 (master)
- [x] 5.3.1 (5.3.x)
- [x] 5.2.2 (5.2.x)
- [x] 5.1.2 (5.1.x)
- [x] 5.0.3 (5.0.x)
- [x] 1.0.7 (1.0.x)

## Final Solution
- Unify line feed codes in this repository to LF.

## Migrating Guide
* Not Required

## Issue Links
* #XXX

**Comment by yoshikawaa** [comment]
@btyanagawamg @hosoitk 
I think that you should consider whether to change the migration guide.
This is because when users copy and paste source code from a new blank project to an application created with an old blank project, it is expected that mixed new line codes will be mixed.

After considering, I will merge these pull request.

**Comment by yoshikawaa** [comment]
Note: @hosoitk decided to merge this.
